export const airlines = [
    "Air Peace",
    "Arik Air",
    "Dana Air",
    "Africa World",
    "Air Cote D'Ivoire",
    "Air France",
    "ASKY",
    "British Airways",
    "Cronos",
    "Delta Airline",
    "Egypt Air",
    "Ethiopian Air",
    "Kenya Air",
    "KLM",
    "Lufthansa",
    "Middle East Air",
    "Qatar Air",
    "Royal Air Marco",
    "Rwanda Air",
    "Saudi Air",
    "South African",
    "TAAG Angola",
    "Turkish Airline",
    "Uganda Air",
    "United Airline",
    "Virgin Atlantic",
    "NG Eagle",
    "Rano Air",
    "Azman",
    "Aero Contractors",
    "Azman Air",
    "Max Air",
    "Ibom Air",
    "Green Africa Airways",
    "United Nigeria Airlines",
    "Overland Airways",
    "Med-View Airline"
  ];
  